// flow-typed signature: bec00c8db517b307543e5119cd89580b
// flow-typed version: <<STUB>>/3d-force-graph_v^1.39.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '3d-force-graph'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "3d-force-graph" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "3d-force-graph/dist/3d-force-graph.common" {
  declare module.exports: any;
}

declare module "3d-force-graph/dist/3d-force-graph" {
  declare module.exports: any;
}

declare module "3d-force-graph/dist/3d-force-graph.min" {
  declare module.exports: any;
}

declare module "3d-force-graph/dist/3d-force-graph.module" {
  declare module.exports: any;
}

declare module "3d-force-graph/rollup.config" {
  declare module.exports: any;
}

declare module "3d-force-graph/rollup.config.module" {
  declare module.exports: any;
}

declare module "3d-force-graph/src/3d-force-graph" {
  declare module.exports: any;
}

declare module "3d-force-graph/src/index" {
  declare module.exports: any;
}

declare module "3d-force-graph/src/kapsule-link" {
  declare module.exports: any;
}

// Filename aliases
declare module "3d-force-graph/dist/3d-force-graph.common.js" {
  declare module.exports: $Exports<"3d-force-graph/dist/3d-force-graph.common">;
}
declare module "3d-force-graph/dist/3d-force-graph.js" {
  declare module.exports: $Exports<"3d-force-graph/dist/3d-force-graph">;
}
declare module "3d-force-graph/dist/3d-force-graph.min.js" {
  declare module.exports: $Exports<"3d-force-graph/dist/3d-force-graph.min">;
}
declare module "3d-force-graph/dist/3d-force-graph.module.js" {
  declare module.exports: $Exports<"3d-force-graph/dist/3d-force-graph.module">;
}
declare module "3d-force-graph/rollup.config.js" {
  declare module.exports: $Exports<"3d-force-graph/rollup.config">;
}
declare module "3d-force-graph/rollup.config.module.js" {
  declare module.exports: $Exports<"3d-force-graph/rollup.config.module">;
}
declare module "3d-force-graph/src/3d-force-graph.js" {
  declare module.exports: $Exports<"3d-force-graph/src/3d-force-graph">;
}
declare module "3d-force-graph/src/index.js" {
  declare module.exports: $Exports<"3d-force-graph/src/index">;
}
declare module "3d-force-graph/src/kapsule-link.js" {
  declare module.exports: $Exports<"3d-force-graph/src/kapsule-link">;
}
