// flow-typed signature: 0793cd07a9b7db70258ebfdae38e67a1
// flow-typed version: <<STUB>>/@tweenjs/tween.js_v^17.2.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tweenjs/tween.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@tweenjs/tween.js" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@tweenjs/tween.js/src/Tween" {
  declare module.exports: any;
}

// Filename aliases
declare module "@tweenjs/tween.js/src/Tween.js" {
  declare module.exports: $Exports<"@tweenjs/tween.js/src/Tween">;
}
